@CCRManager_HostAddress = http://localhost:5008


# https://localhost:7028/api/CommonContainerRegistry/token?name=token1
GET {{CCRManager_HostAddress}}/api/CommonContainerRegistry/token?name=token1 Http/1.1
###

# https://localhost:7028/api/CommonContainerRegistry/scopemaps
PUT {{CCRManager_HostAddress}}/api/CommonContainerRegistry/scopemaps HTTP/1.1
Content-Type: application/json
{
  "name": "ReadWrite",
  "description": "A scope map for read write",
  "permissions": [
    "content/read",
    "content/write",
    "metadata/read"
  ]
}
###

# https://localhost:7028/api/CommonContainerRegistry/token
PUT {{CCRManager_HostAddress}}/api/CommonContainerRegistry/token HTTP/1.1
Content-Type: application/json
{
  "tokenName": "token4",
  "scopeMapName": "acrReadWrite",
  "status": "enabled"
}
###

# https://localhost:7028/api/CommonContainerRegistry/password
PUT {{CCRManager_HostAddress}}/api/CommonContainerRegistry/password HTTP/1.1
Content-Type: application/json
{
  "tokenName": "token3",
  "passwordExpiryDate": "04/10/2025 12:12:12"
}
### MM/dd/yyyy HH:MM:SS
###